{% set version = "0.1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sparsebn
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sparsebn_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sparsebn/sparsebn_{{ version }}.tar.gz
  sha256: 85f1b4c912ed27db5ac4ae7defcfb79ddc7494be1df7239499ac573b6c0026ac

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ccdralgorithm >=0.0.4
    - r-discretecdalgorithm >=0.0.5
    - r-sparsebnutils >=0.0.5
  run:
    - r-base
    - r-ccdralgorithm >=0.0.4
    - r-discretecdalgorithm >=0.0.5
    - r-sparsebnutils >=0.0.5

test:
  commands:
    - $R -e "library('sparsebn')"           # [not win]
    - "\"%R%\" -e \"library('sparsebn')\""  # [win]

about:
  home: https://github.com/itsrainingdata/sparsebn
  license: GPL-2
  summary: Fast methods for learning sparse Bayesian networks from high-dimensional data using sparse regularization, as described in Aragam, Gu, and Zhou (2017) <arXiv:1703.04025>. Designed to handle mixed experimental and observational data with thousands of variables with either continuous or discrete observations.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: sparsebn
# Title: Learning Sparse Bayesian Networks from High-Dimensional Data
# Version: 0.1.0
# Date: 2019-11-05
# Authors@R: c( person("Bryon", "Aragam", email = "sparsebn@gmail.com", role = c("aut", "cre")), person("Jiaying", "Gu", role = c("aut")), person("Dacheng", "Zhang", role = c("aut")), person("Qing", "Zhou", role = c("aut")) )
# Maintainer: Bryon Aragam <sparsebn@gmail.com>
# Description: Fast methods for learning sparse Bayesian networks from high-dimensional data using sparse regularization, as described in Aragam, Gu, and Zhou (2017) <arXiv:1703.04025>. Designed to handle mixed experimental and observational data with thousands of variables with either continuous or discrete observations.
# Depends: R (>= 3.2.3), sparsebnUtils (>= 0.0.5), ccdrAlgorithm (>= 0.0.4), discretecdAlgorithm (>= 0.0.5)
# Suggests: knitr, rmarkdown, mvtnorm, igraph, graph, testthat
# URL: https://github.com/itsrainingdata/sparsebn
# BugReports: https://github.com/itsrainingdata/sparsebn/issues
# License: GPL (>= 2)
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# LazyData: true
# NeedsCompilation: no
# Packaged: 2019-11-04 18:25:46 UTC; naragam
# Author: Bryon Aragam [aut, cre], Jiaying Gu [aut], Dacheng Zhang [aut], Qing Zhou [aut]
# Repository: CRAN
# Date/Publication: 2019-11-04 19:50:02 UTC
