appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Bud2UhIv3EVD9zKEWOPaMW0imGnBbSWo0T9gt+Tv7ZtMlUCHISUmWrWFrhtK0yuSjwVJIIHriUL8rL/n68Gg6dMSLvrcH4Ck8sl49IISs3O6JBfWDMeFJ3TmS0a4hHLdvKPcz0HaIjq4h4TCtNJKK7bhnPQgcUL9gRVHQS7QYC68BEkP90uQP+Xgp26HArpUozg8RY+J73KIgln37mKh0OQrkAm7nuJjm3I7PzsegjGP3uCZp8iNAspjdrQe57hj53BJTtPZGUmEc8OOV0mWTu3qKsuAUCVrmLPI9Qx0e4j2qeTBVrOGZubR+UYq2JfyyjBBXgvja4EaWfqQkj6WFjFWl8cNT0RUF0qaxV/55lID6B1CMa61lf3ACGsITYwfg9ekS07bjoIUg5SQDLrHChYeEg7E0ROSozWiJzQaxGIp7+4obCM4W/Q624Xt+DRdiK+D+9wv1/RVB8sqI4WXyHQD5f+JdO++VqArKHjFsH+o5O/9eLkVcMwnoEafuNBSn9PmERHJIfVgqhJGe5YNWgAmNpDm4bwBLM0srJAF1ufQfxZrmfDr8ZBPnba/nNgi2JF0F2Iv7V+8s3xNyeZAts+v50JsgzUOOM+OBGlClXrBylhzoeYaiKjFhCQAbJTvnbAx2xC/fIbYxwTyvB8Z+8CyItAHeyGHosDJ0Kv/R8Q=}
bot:
  automerge: true
